// This code is automatically generated by mparse. Do not edit.

// Source grammar:
//
// Root<std::string>
//     : 'x' { $$ = $1 }

#include <any>
#include <cstddef>
#include <iterator>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <variant>
#include <vector>

namespace mparse_generated_detail {
    template <typename Value>
    struct Result {
        size_t position = 0;
        Value value{};
    };

    struct PartialResult {
        size_t position = 0;
        std::vector<std::any> stack;
    };

    template <typename Value>
    const Value& semanticValue(const std::vector<std::any>& args, size_t index) {
        return std::any_cast<const Value&>(args.at(index));
    }

    template <typename Value>
    void appendAll(std::vector<Value>& target, std::vector<Value>&& source) {
        target.insert(target.end(), std::make_move_iterator(source.begin()), std::make_move_iterator(source.end()));
    }
} // namespace mparse_generated_detail

static std::vector<mparse_generated_detail::Result<std::string>> mparse_parse_Root(std::string_view input, size_t position);
static std::vector<mparse_generated_detail::PartialResult> mparse_parse_Root_vertex_0(std::string_view input, size_t position, std::vector<std::any> stack);
static std::vector<mparse_generated_detail::PartialResult> mparse_parse_Root_vertex_1(std::string_view input, size_t position, std::vector<std::any> stack);
static std::vector<mparse_generated_detail::PartialResult> mparse_parse_Root_vertex_2(std::string_view input, size_t position, std::vector<std::any> stack);

static std::any mparse_action_0(const std::vector<std::any>& args) {
    std::string ret{};
    ret = mparse_generated_detail::semanticValue<std::string>(args, 0);
    return ret;
}

static std::vector<mparse_generated_detail::Result<std::string>> mparse_parse_Root(std::string_view input, size_t position) {
    std::vector<mparse_generated_detail::Result<std::string>> results;
    for (auto&& partial : mparse_parse_Root_vertex_0(input, position, {})) {
        if (partial.stack.empty()) {
            continue;
        }
        results.push_back(mparse_generated_detail::Result<std::string>{
            .position = partial.position,
            .value = std::any_cast<std::string>(partial.stack.back()),
        });
    }
    return results;
}

static std::vector<mparse_generated_detail::PartialResult> mparse_parse_Root_vertex_0(std::string_view input, size_t position, std::vector<std::any> stack) {
    std::vector<mparse_generated_detail::PartialResult> results;
    {
        const std::string_view literal = "x";
        if (input.substr(position, literal.size()) == literal) {
            auto next_stack = stack;
            next_stack.push_back(std::string{literal});
            auto next_results = mparse_parse_Root_vertex_2(input, position + literal.size(), std::move(next_stack));
            mparse_generated_detail::appendAll(results, std::move(next_results));
        }
    }
    return results;
}

static std::vector<mparse_generated_detail::PartialResult> mparse_parse_Root_vertex_1(std::string_view input, size_t position, std::vector<std::any> stack) {
    std::vector<mparse_generated_detail::PartialResult> results;
    if (!stack.empty()) {
        results.push_back(mparse_generated_detail::PartialResult{
            .position = position,
            .stack = stack,
        });
    }
    return results;
}

static std::vector<mparse_generated_detail::PartialResult> mparse_parse_Root_vertex_2(std::string_view input, size_t position, std::vector<std::any> stack) {
    std::vector<mparse_generated_detail::PartialResult> results;
    {
        std::vector<std::any> next_stack{mparse_action_0(stack)};
        auto next_results = mparse_parse_Root_vertex_1(input, position, std::move(next_stack));
        mparse_generated_detail::appendAll(results, std::move(next_results));
    }
    return results;
}

std::optional<std::string> parse(std::string_view input) {
    for (const auto& result : mparse_parse_Root(input, 0)) {
        if (result.position == input.size()) {
            return result.value;
        }
    }
    return std::nullopt;
}
